const ADD_KNOW = "ADD_KNOW";
const DELETE_KNOW = "DELETE_KNOW";
const GET_KNOW_LIST = "GET_KNOW_LIST";
const UPDATE_KNOW = "UPDATE_KNOW";
const CHANGE_KNOW_VALUE = "CHANGE_KNOW_VALUE";
const HANDLE_KNOW_EDIT = "HANDLE_KNOW_EDIT";

export default {
  CHANGE_KNOW_VALUE,
  HANDLE_KNOW_EDIT,
  ADD_KNOW,
  DELETE_KNOW,
  GET_KNOW_LIST,
  UPDATE_KNOW
};
